#!/usr/bin/zsh

# por ahora, lo único que hace tiempo es abrir tomate.
bspc rule -a st state=floating -o rectangle=720x720+600+220 && st -e tomate.py

 #Names to display
#files_array=(
	#"notas"
	#"diario"
	#"config"
	#"vimwiki"
	#"pdf"
	#"tomate"
	 #"nvim"
	 #"sxhkd"
	 #"bspwm"
	 #"polybar"
	 #"vifm"
	#)

# !/bin/sh
 #Format de names to display
#files=$''
#for f in "${files_array[@]}"; do
	#files=$f$'\n'$files
#done

 #Dmenu
#choose_file=$(echo "$files" | dmenu -h 35 -i -p "Brainhub")

 #What name execute what
#case $choose_file in

   #nvim)
  #pdf)
	#bspc rule -a St -o state=floating rectangle=720x720+600+220 && st -e pdf_menu
	 #st -e nvim $HOME/.config/nvim/init.vim
	#;;

  #tomate)
	#bspc rule -a St -o state=floating rectangle=720x720+600+220 && st -e tomate
	#;;

  #vimwiki)
	#st -e nvim -c "VimwikiIndex"
	#;;

  #config)
	#bspc rule -a St -o state=floating rectangle=720x720+600+220 && st -e config_menu
	#;;

  #diario)
	#st -e diario
	#;;

  #notas)
		#bspc rule -a St -o state=floating rectangle=720x720+600+220 && st -e notas
	#;;

  #*)
#esac
