#!/usr/bin/env python3
import os
import time
import json
from datetime import datetime, timedelta
from datetime import date as dt_date

# bh_folder = os.environ.get("brainhub_folder")

home = os.environ.get('HOME')
dir_path = home

with open(f'{dir_path}/log_tomates.json') as json_registro:
    tomates_dict = json.load(json_registro)
# ---------
f2date = lambda date: datetime.strptime(date, '%d/%m/%Y')
f2str = lambda date: date.strftime('%d/%m/%Y')

today = f2str(dt_date.today())

if today in tomates_dict:
    # today_toms = (sum([len(tomcat) for tomcat in
                  # tomates_dict[today].values()]))
    today_toms = sum(tomates_dict[today].values())
else:
    today_toms = 0

# msg = "\|" + "O"*today_toms+"\|"
# msg = f"tomates hoy: {today_toms}"
msg = today_toms

os.system(f"echo {msg}")
# os.system('motivation.py')
